name: Build

on:
  push:
    branches:
     - main
    tags:
    - v*
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build & package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Package
        run: dotnet pack src/GovUk.OneLogin.AspNetCore/ --configuration Release --no-build
        env:
          MINVERBUILDMETADATA: ${{ env.GITHUB_RUN_NUMBER }}

      - name: Publish package artifact
        uses: actions/upload-artifact@v3
        with:
          name: GovUk.OneLogin.AspNetCore.nupkg
          path: src/GovUk.OneLogin.AspNetCore/bin/Release/*.nupkg

  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Download package artifact
      uses: actions/download-artifact@v3
      with:
        name: GovUk.OneLogin.AspNetCore.nupkg

    - name: Publish package to NuGet
      run: dotnet nuget push **/*.nupkg --api-key $NUGET_TOKEN --source https://api.nuget.org/v3/index.json --skip-duplicate
      env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
